GS_HOME=~/workspace/SGTest/tools/gigaspaces

GS_AGENT_PATH=$GS_HOME/bin/gs-agent.sh
GS_AGENT_ARGUMENTS="gsa.gsc 0 gsa.lus 1 gsa.gsm 0 gsa.global.gsc 0 gsa.global.gsm 0 gsa.global.lus 0"
GS_AGENT_COMMAND="$GS_AGENT_PATH $GS_AGENT_ARGUMENTS" 

ISREAL_GROUP=israel-$USER
LONDON_GROUP=london-$USER
NY_GROUP=ny-$USER

LOOKUPGROUPS=$ISREAL_GROUP
export LOOKUPGROUPS
$GS_AGENT_COMMAND &
LOOKUPGROUPS=$LONDON_GROUP
export LOOKUPGROUPS 
$GS_AGENT_COMMAND &
LOOKUPGROUPS=$NY_GROUP
export LOOKUPGROUPS
$GS_AGENT_COMMAND &

